name: Tests

on: push

jobs:


  tests:
    name: Unit Testing
    runs-on: windows-2025
    steps:
    # Step 1: Verify Docker Installation
      - name: Check Docker Version
        run: |
          wsl --update
          wsl --install -d Ubuntu
          wsl sudo apt-get update -y
          wsl sudo apt-get install -y docker.io

      - uses: actions/checkout@v2.1.0
      - run: dotnet test
      