name: Tests

on: push

jobs:


  tests:
    name: Unit Testing
    runs-on: windows-2025
    steps:
    # Step 1: Verify Docker Installation
      - name: Enable WSL2 and install dependencies
        run: |
          wsl --update
          wsl --install -d Ubuntu
          wsl sudo apt-get update -y
          wsl sudo apt-get install -y docker.io

      - name: Start Docker inside WSL2
        run: |
          wsl sudo service docker start
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Check Docker is running
        run: wsl docker info

      - uses: actions/checkout@v2.1.0
      - run: dotnet test
      