name: Db Local
jobs:
  build:
  name: blah
  runs-on: windows-latest
  steps:
    - name: Checking local db version
      run: |
        sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
